config/routes.rb
Rails.application.routes.draw do
  resources :houses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/house.rb
class House < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[ show edit update destroy ]

  # GET /houses or /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1 or /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses or /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to house_url(@house), notice: "House was successfully created." }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1 or /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to house_url(@house), notice: "House was successfully updated." }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1 or /houses/1.json
  def destroy
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url, notice: "House was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def house_params
      params.require(:house).permit(:name, :address, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house) do |form| %>
  <% if house.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.text_field :picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/_house.html.erb
<div id="<%= dom_id house %>">
  <p>
    <strong>Name:</strong>
    <%= house.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= house.address %>
  </p>

  <p>
    <strong>Picture:</strong>
    <%= image_tag(house.picture, :width => 100, :height => 100) %>
  </p>

</div>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render "form", house: @house %>

<br>

<div>
  <%= link_to "Show this house", @house %> |
  <%= link_to "Back to houses", houses_path %>
</div>

app/views/houses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Houses</h1>

<div id="houses">
  <% @houses.each do |house| %>
    <%= render house %>
    <p>
      <%= link_to "Show this house", house %>
    </p>
  <% end %>
</div>

<%= link_to "New house", new_house_path %>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render "form", house: @house %>

<br>

<div>
  <%= link_to "Back to houses", houses_path %>
</div>

app/views/houses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @house %>

<div>
  <%= link_to "Edit this house", edit_house_path(@house) %> |
  <%= link_to "Back to houses", houses_path %>

  <%= button_to "Destroy this house", @house, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Houses</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>